---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Run yarn install
        run: yarn install

      - name: Lint the code
        run: yarn lint

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
              -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: mikededeckerstudent/webapp:latest