---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Run yarn install
        run: yarn install

      - name: Lint the code
        run: yarn lint