---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Read node from package.json
        uses: josepdecid/get-nodejs-version@<VERSION>
        id: get-node-version