---
name: Build and test
on:
  push:
    branches:
      - main
env:
  MYSQLDB_USER: root
  MYSQLDB_ROOT_PASSWORD: root
  MYSQLDB_LOCAL_PORT: 3377
  MYSQLDB_DOCKER_PORT: 3306
  MYSQLDB_DATABASE: animals
  MYSQLDB_URL: "server=localhost:$MYSQLDB_LOCAL_PORT;uid=$MYSQLDB_USER;pwd=$MYSQLDB_ROOT_PASSWORD;database=$MYSQLDB_DATABASE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Run yarn install
        run: yarn install

      - name: Lint the code
        run: yarn lint

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mikededeckerstudent/webapp:latest

      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          # https://docs.docker.com/compose/reference/overview/
          cli-args: "up"

      - name: Extra yarn test
        run: yarn test